name: Build DEB Package

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev

      - name: Install Python deps
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build app (Linux binary)
        run: |
          pyinstaller --onedir --noconsole \
            --add-data "vgca.png:." \
            --add-data "bit4id.png:." \
            --add-data "safenet.png:." \
            --hidden-import fitz \
            --hidden-import PIL \
            --name vgca-signer \
            main.py

      - name: Copy binary vào build_deb
        run: |
          mkdir -p build_deb/opt/vgca-signer
          cp -r dist/vgca-signer/. build_deb/opt/vgca-signer/
          chmod +x build_deb/opt/vgca-signer/vgca-signer
          chmod +x build_deb/usr/bin/vgca-signer

      - name: Build .deb
        run: dpkg-deb --build build_deb vgca-signer.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: vgca-signer.deb

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: vgca-signer.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
